from tkinter import *
win = Tk()
win.title('my first application')
win.geometry('600x400+100+100')
l= Label(win, text='Name')
l.pack()
b = Button(win, text= 'Click me')
b.pack()
e = Entry(win)
e.pack()
t = Text(win, width=30, height=10)
t.pack()
c= Radiobutton(win, text='yes')
c.pack()
c1= Radiobutton(win, text='No')
c1.pack()
o= OptionMenu(win, 'var','python',*('java','python','c++'))
o.pack()

win.mainloop()